language: generic
sudo: required
services: 
  - docker

before_install:
  docker build -t matiz11111/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true matiz11111/docker-react npm run test